config/routes.rb
Rails.application.routes.draw do
  resources :student
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
    def new
        @student = Student.new
        @student = Student.new(name: ' ')
    end

    def create
        student =  Student.new(student_params)
        student.save
        flash[:notice] = "Student has been created"
        redirect_to student_path
    end
    def index
        @student = Student.all
    end
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KejarId</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student/index.html.erb
<% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>
<table>
    <tr>
        <td>Name<td>
        <td>Username<td>
    </tr>
    <% @student.each do |s|%>
    <tr>
        <td><%= s.name %></td>
        <td><%= s.username %><td>
        <td><%= link_to 'Detail', student_path(s) %> | <%= link_to 'Edit', edit_student_path(s) %><td>
        <td><%= link_to 'Delete', s , method: :delete, data: {confirm: 'Are you sure?'} %><td>
    </tr>
    <% end %>
</table>

<%= link_to 'New Student', new_student_path() %>

app/views/student/new.html.erb
<%= form_for(@student) do |f| %>
    <%= f.label :name %> </br>
    <%= f.text_field :name %> </br>

    <%= f.label :username %> </br>
    <%= f.text_field :username %> </br>

    <%= f.label :age %> </br>
    <%= f.text_field :age %> </br>

    <%= f.label :kelas %> </br>
    <%= f.text_field :kelas %> </br>

    <%= f.label :address %> </br>
    <%= f.text_field :address %> </br>

    <%= f.label :city %> </br>
    <%= f.text_field :city %> </br>

    <%= f.label :nik %> </br>
    <%= f.text_field :nik %> </br>


    <%= f.submit "Save" %>
<% end %>